matrix:
  include:
  # Native Builds
    - language: c
      os: linux
      env: BUILD=native CC=gcc CXX=g++ FRAMEWORK=SDL
      
    - os: linux
      env: BUILD=native CC=clang CXX=clang++ FRAMEWORK=SDL
      language: c
      
    - os: osx
      env: BUILD=native CC=clang CXX=clang++ FRAMEWORK=SDL
      language: c
      
    - os: linux
      env: BUILD=native CC=gcc CXX=g++ FRAMEWORK=SDL2 
      language: c
      
    - os: linux
      env: BUILD=native CC=clang CXX=clang++ FRAMEWORK=SDL2
      language: c
     
    - os: osx
      env: BUILD=native CC=clang CXX=clang++ FRAMEWORK=SDL2
      language: c

    - os: linux
      env: BUILD=android 
      language: ruby
      services:
        - docker

    - os: osx
      env: BUILD=IOS
      language: c
      
    - os: linux 
      env: BUILD=emscripten 
      language: ruby
      services:
        - docker
      
    - os: linux
      env: BUILD=psp
      language: ruby
      services:
        - docker
       
    - os: linux
      env: BUILD=dreamcast
      language: ruby
      services:
        - docker
      
    - os: linux
      env: BUILD=vita
      language: ruby
      services:
        - docker

install:   
    - if [ "$BUILD" == "vita" ]; then docker build -t plutoboy_vita -f build/Vita/Dockerfile .; fi 
    - if [ "$BUILD" == "vita" ]; then docker run plutoboy_vita; fi
    
    - if [ "$BUILD" == "psp" ]; then docker build -t plutoboy_psp -f build/PSP/Dockerfile . ; fi
    - if [ "$BUILD" == "psp" ]; then docker run plutoboy_psp; fi
    
    - if [ "$BUILD" == "emscripten" ]; then docker build -t plutoboy_js -f build/Javascript/Dockerfile . ; fi 
    - if [ "$BUILD" == "emscripten" ]; then docker run plutoboy_js; fi 
   
    - if [ "$BUILD" == "dreamcast" ]; then docker build -t plutoboy_dc -f build/Dreamcast/Dockerfile . ; fi 
    - if [ "$BUILD" == "dreamcast" ]; then docker run plutoboy_dc; fi

    - if [ "$BUILD" == "android" ]; then docker build -t plutoboy_android -f build/Android/Dockerfile . ; fi
    - if [ "$BUILD" == "android" ]; then docker run plutoboy_android; fi

     # Native Linux build setup
    - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$BUILD" = "native" ]; then sudo apt-get update; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$BUILD" = "native" ]; then sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$BUILD" == "native" ]; then sudo apt-get install scons; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$FRAMEWORK" == "SDL" ]; then sudo apt-get -f install libsdl1.2-dev libsdl-net1.2-dev; fi
    
    - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$FRAMEWORK" == "SDL2" ]; then sudo apt-get -f install libsdl2-dev libsdl2-net-dev; fi


    # Native OSX Build setup
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$BUILD" == "native" ]; then brew install scons; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install sdl sdl2 sdl_net sdl2_net; fi

#Setup SDL2 framework for XCode IOS
    - if [ "$BUILD" == "IOS" ]; then git clone https://github.com/manifest/sdl-ios-framework; fi
    - if [ "$BUILD" == "IOS" ]; then cd sdl-ios-framework; fi 
    - if [ "$BUILD" == "IOS" ]; then gem install colorize; fi 
    - if [ "$BUILD" == "IOS" ]; then rake SDL2:build; fi
    - if [ "$BUILD" == "IOS" ]; then mkdir ~/Library/Frameworks/; fi 
    - if [ "$BUILD" == "IOS" ]; then cp -r build/sdl/SDL2.framework ~/Library/Frameworks/; fi


script:
    # Native builds
    - if [ "$BUILD" == "native" ]; then cd build/Unix; fi
    - if [ "$BUILD" == "native" ]; then scons cc=$CC framework=$FRAMEWORK mode=$MODE; fi
    
    # IOS Builds
    - if [ "$BUILD" == "IOS" ]; then cd ~/build/RossMeikleham/PlutoBoy/build/IOS; fi
    - if [ "$BUILD" == "IOS" ]; then xcodebuild -project Plutoboy.xcodeproj -target Plutoboy -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO; fi
