version: '{branch}-{build}'

environment:

  matrix:
    - platform: x64 
      PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.10
      PYTHON_ARCH: "64"
      FRAMEWORK: "SDL"

    - platform: x64 
      PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.10
      PYTHON_ARCH: "64"
      FRAMEWORK: "SDL2"

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - easy_install scons

build_script:
    - python --version
    - scons --version
    - cd build/Windows/scons
    - scons framework=%FRAMEWORK%
